hydra:
  run:
    dir: ./outputs/${blur.exp_name}/${now:%Y-%m-%d-%H-%M-%S}/
blur:
  exp_name: test
  model:
    warmup: null
    cnn:
      pretrained: /model_zoo/best5.pt
      depth: 12
      in_chans: 3
      out_chans: 3
      init_feats: 64
      kernel_size: 3
    red:
      gamma: 1
      tau: 0.00095
    deq:
      kwargs:
        tol: 1e-5
  data:
    train_path: /DIV2K_A
    val_path: /Set5
    three_imgs_path: /set3c
    kernel_path: /kernels/L09.mat
    kernel_type: k4
    fixed_noise: true
    sigma: 2.55
    patch_size: 256
    patch_per_img: 2
    batch_size: 2
    num_workers: 8
    test_overlap: 30
  train:
    num_epoches: 30

    devices: [0]
    optimizer:
      type: Adam
      kwargs:
        lr: 5e-4
    scheduler:
      type: MultiStepLR
      kwargs:
        milestones: [8]
        gamma: 1e-4/5e-4
    