hydra:
  run:
    dir: ./outputs/${blur.exp_name}/${now:%Y-%m-%d-%H-%M-%S}/
blur:
  exp_name: best5
  model:
    warmup: null
    cnn:
      pretrained: /export1/project/zihao/DEQ_Blur/best5.pt
      depth: 12
      in_chans: 3
      out_chans: 3
      init_feats: 64
      kernel_size: 3
    red:
      gamma: 1
      tau: 0.00095
    deq:
      kwargs:
        tol: 1e-5
  data:
    hard_disk: "."
    train_path: /export1/project/Data_shirin/Data/Set5 #["/export1/project/Data_shirin/Data/DIV2K","/export1/project/Data_shirin/Data/CBSD400"]
    val_path: /export1/project/Data_shirin/Data/Set5
    three_imgs_path: /export1/project/zihao/DEQ_Blur/set3c
    kernel_path: /export1/project/zihao/DEQ_Blur/kernels/L09.mat
    kernel_type: k4
    fixed_noise: true
    sigma: 2.55
    patch_size: 256
    patch_per_img: 5
    batch_size: 8
    num_workers: 8
    test_overlap: 30
  train:
    num_epoches: 30

    devices: [0,1]
    optimizer:
      type: Adam
      kwargs:
        lr: 5e-4
    scheduler:
      type: MultiStepLR
      kwargs:
        milestones: [8]
        gamma: 1e-4/5e-4
    